import { Building2, Car, UserRound } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useApp } from '../context/AppContext'
import { PageHeader, SearchBox, StatusBadge } from '../components/ui'

type Catalog = 'employees' | 'vehicles' | 'departments'
export function Catalogs() {
  const { catalogs: { departments, employees, vehicles }, live } = useApp()
  const [tab, setTab] = useState<Catalog>('employees'); const [search, setSearch] = useState('')
  const filteredEmployees = useMemo(() => employees.filter((e) => `${e.code} ${e.name} ${e.department}`.toLowerCase().includes(search.toLowerCase())), [employees, search])
  const filteredVehicles = useMemo(() => vehicles.filter((v) => `${v.plate} ${v.code} ${v.brand} ${v.model} ${v.department}`.toLowerCase().includes(search.toLowerCase())), [vehicles, search])
  const filteredDepartments = useMemo(() => departments.filter((d) => `${d.code} ${d.name}`.toLowerCase().includes(search.toLowerCase())), [departments, search])
  return <div className="page"><PageHeader eyebrow="Configuración" title="Catálogos organizacionales" description={live ? 'Consulta empleados, vehículos y departamentos del backend.' : 'Consulta de empleados, vehículos y departamentos de demostración.'} /><div className="tabs"><button className={tab === 'employees' ? 'active' : ''} onClick={() => setTab('employees')}><UserRound size={17} /> Empleados <span>{employees.length}</span></button><button className={tab === 'vehicles' ? 'active' : ''} onClick={() => setTab('vehicles')}><Car size={17} /> Vehículos <span>{vehicles.length}</span></button><button className={tab === 'departments' ? 'active' : ''} onClick={() => setTab('departments')}><Building2 size={17} /> Departamentos <span>{departments.length}</span></button></div><section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder={`Buscar ${tab === 'employees' ? 'empleados' : tab === 'vehicles' ? 'vehículos' : 'departamentos'}…`} /></div><div className="table-scroll">
    {tab === 'employees' && <table><thead><tr><th>Empleado</th><th>Documento</th><th>Departamento / cargo</th><th>Contacto</th><th>Estado</th></tr></thead><tbody>{filteredEmployees.map((e) => <tr key={e.id}><td><div className="person-cell"><span className="initials">{e.name.split(' ').map((n) => n[0]).slice(0, 2).join('')}</span><span><strong>{e.name}</strong><small>{e.code}</small></span></div></td><td>{e.document}</td><td><strong>{e.department}</strong><small>{e.position}</small></td><td>{e.email}<small>{e.phone}</small></td><td><StatusBadge value={e.active ? 'ACTIVO' : 'INACTIVO'} /></td></tr>)}</tbody></table>}
    {tab === 'vehicles' && <table><thead><tr><th>Vehículo</th><th>Ficha</th><th>Departamento</th><th>Capacidad</th><th>Odómetro</th><th>Estado</th></tr></thead><tbody>{filteredVehicles.map((v) => <tr key={v.id}><td><strong>{v.plate}</strong><small>{v.brand} {v.model} · {v.year}</small></td><td>{v.code}<small>{v.type}</small></td><td>{v.department}</td><td>{v.tankCapacity} gal</td><td>{v.odometer.toLocaleString()} km</td><td><StatusBadge value={v.active ? 'ACTIVO' : 'INACTIVO'} /></td></tr>)}</tbody></table>}
    {tab === 'departments' && <table><thead><tr><th>Departamento</th><th>Código</th><th>Empleados</th><th>Vehículos</th><th>Estado</th></tr></thead><tbody>{filteredDepartments.map((d) => <tr key={d.id}><td><strong>{d.name}</strong></td><td>{d.code}</td><td>{d.employees}</td><td>{d.vehicles}</td><td><StatusBadge value={d.active ? 'ACTIVO' : 'INACTIVO'} /></td></tr>)}</tbody></table>}
  </div></section></div>
}
