import { Camera, CheckCircle2, Fuel, QrCode, RotateCcw, ScanLine, ShieldCheck, XCircle } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useApp } from '../context/AppContext'
import { PageHeader, StatusBadge } from '../components/ui'
import type { Ticket } from '../types'

export function Dispatch() {
  const { tickets, tanks, dispatchTicket, notify, live } = useApp()
  const [code, setCode] = useState('')
  const [ticket, setTicket] = useState<Ticket | null>(null)
  const [invalid, setInvalid] = useState(false)
  const [completed, setCompleted] = useState(false)
  const validate = (value = code) => { const found = tickets.find((item) => item.sequence.toLowerCase() === value.trim().toLowerCase()); setTicket(found ?? null); setInvalid(!found); setCompleted(false) }
  const simulateScan = () => { const candidate = tickets.find((item) => ['CREADO', 'ENVIADO', 'PENDIENTE', 'PROXIMO_A_VENCER'].includes(item.status)); if (candidate) { setCode(candidate.sequence); validate(candidate.sequence) } }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!ticket) return; const data = new FormData(event.currentTarget); try { if (await dispatchTicket(ticket.sequence, Number(data.get('tank')), Number(data.get('gallons')), Number(data.get('odometer')))) setCompleted(true); else notify('No se pudo despachar', 'Revisa vigencia, estado, cantidad y existencia del tanque.', 'error') } catch (cause) { notify('No se pudo despachar', cause instanceof Error ? cause.message : 'Error de la API.', 'error') } }
  const reset = () => { setCode(''); setTicket(null); setInvalid(false); setCompleted(false) }
  if (live) return <div className="page dispatch-page"><PageHeader eyebrow="Punto de despacho" title="Despacho por QR" description="Por seguridad, el despacho conectado se realiza con lectura y validación del QR en el punto de suministro." /><section className="panel" style={{ padding: 32 }}><ShieldCheck size={36} /><h2>Validación en el punto de suministro</h2><p>La web administrativa no permite consumir tickets por número: ese dato no demuestra posesión del QR. Aquí puedes consultar sus estados e inventario; usa el flujo de escaneo autorizado para registrar el despacho.</p></section></div>
  return <div className="page dispatch-page"><PageHeader eyebrow="Punto de despacho" title="Simulación de despacho" description="Prueba el flujo con tickets de demostración; no valida un QR real." />
    <section className="dispatch-shell"><div className="scanner-panel"><div className="scanner-frame"><ScanLine size={68} /><span /><p>Escaneo simulado con datos locales</p></div><button className="camera-button" onClick={simulateScan}><Camera size={19} /> Simular escaneo QR</button><div className="divider"><span>o ingresa el número</span></div><div className="manual-code"><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="COM-2026-000000" /><button onClick={() => validate()}>Buscar</button></div><div className="online-state"><i /><span><strong>Modo demostración</strong><small>No valida códigos reales</small></span><ShieldCheck size={18} /></div></div>
      <div className="validation-panel">{!ticket && !invalid && <div className="validation-placeholder"><div><QrCode size={44} /></div><h2>Esperando un ticket</h2><p>Ingresa el número o prueba el escaneo simulado para comenzar.</p></div>}{invalid && <div className="validation-placeholder error"><div><XCircle size={44} /></div><h2>Ticket no encontrado</h2><p>Verifica el número e inténtalo nuevamente.</p><button className="secondary-button" onClick={reset}><RotateCcw size={17} /> Intentar de nuevo</button></div>}{ticket && !completed && <form className="dispatch-form" onSubmit={submit}><div className="valid-heading"><CheckCircle2 size={30} /><span><strong>Ticket encontrado</strong><small>Datos de demostración; sin validación criptográfica</small></span><StatusBadge value={ticket.status} /></div><dl className="dispatch-ticket-data"><div><dt>Ticket</dt><dd>{ticket.sequence}</dd></div><div><dt>Empleado</dt><dd>{ticket.employee}</dd></div><div><dt>Vehículo</dt><dd>{ticket.vehicle}</dd></div><div><dt>Autorizado</dt><dd>{ticket.gallons} gal</dd></div><div><dt>Combustible</dt><dd>{ticket.fuelType}</dd></div><div><dt>Departamento</dt><dd>{ticket.department}</dd></div></dl><div className="dispatch-fields"><label>Tanque<select name="tank" required>{tanks.filter((tank) => tank.fuelType === ticket.fuelType).map((tank) => <option value={tank.id} key={tank.id}>{tank.code} · {tank.stock} gal</option>)}</select></label><label>Galones servidos<input name="gallons" type="number" min="0.1" max={ticket.gallons} step="0.1" defaultValue={ticket.gallons} required /></label><label>Odómetro actual<input name="odometer" type="number" min="0" required /></label><label className="identity-check"><input type="checkbox" required /> Identidad del conductor confirmada</label></div><button className="primary-button dispatch-submit" disabled={new Date(ticket.expiresAt).getTime() <= Date.now() || !['CREADO', 'ENVIADO', 'PENDIENTE', 'PROXIMO_A_VENCER'].includes(ticket.status)}><Fuel size={18} /> Confirmar despacho</button></form>}{completed && <div className="validation-placeholder success"><div><CheckCircle2 size={48} /></div><h2>Despacho registrado</h2><p>El ticket de demostración quedó consumido y el inventario local se actualizó.</p><button className="primary-button" onClick={reset}>Procesar otro ticket</button></div>}</div>
    </section></div>
}
