import { ArrowDownRight, ArrowUpRight, Download, Filter } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useApp } from '../context/AppContext'
import { downloadCsv, formatDate, PageHeader, SearchBox } from '../components/ui'

export function Operations() {
  const { movements } = useApp(); const [search, setSearch] = useState(''); const [type, setType] = useState('TODOS')
  const filtered = useMemo(() => movements.filter((movement) => (type === 'TODOS' || movement.type === type) && `${movement.tank} ${movement.reference} ${movement.user}`.toLowerCase().includes(search.toLowerCase())), [movements, search, type])
  return <div className="page"><PageHeader eyebrow="Combustible" title="Movimientos de inventario" description="Consulta las entradas, salidas, ajustes y mermas recientes." actions={<button className="secondary-button" onClick={() => downloadCsv('movimientos-inventario.csv', [['Fecha', 'Tipo', 'Tanque', 'Galones', 'Referencia', 'Usuario'], ...filtered.map((m) => [m.date, m.type, m.tank, m.gallons, m.reference, m.user])])}><Download size={17} /> Exportar CSV</button>} /><section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Buscar tanque, referencia o usuario…" /><label className="select-wrap"><Filter size={16} /><select value={type} onChange={(event) => setType(event.target.value)}><option value="TODOS">Todos los movimientos</option><option>ENTRADA</option><option>SALIDA</option><option>AJUSTE_POSITIVO</option><option>AJUSTE_NEGATIVO</option><option>MERMA</option></select></label></div><div className="table-scroll"><table><thead><tr><th>ID / fecha</th><th>Tipo</th><th>Tanque</th><th>Cantidad</th><th>Existencia</th><th>Referencia</th><th>Responsable</th></tr></thead><tbody>{filtered.map((m) => <tr key={m.id}><td><strong>#{m.id}</strong><small>{formatDate(m.date, true)}</small></td><td><span className={`movement-type ${m.type === 'SALIDA' || m.type.includes('NEGATIVO') ? 'out' : 'in'}`}>{m.type === 'SALIDA' || m.type.includes('NEGATIVO') ? <ArrowDownRight size={16} /> : <ArrowUpRight size={16} />}{m.type.replace('_', ' ')}</span></td><td><strong>{m.tank}</strong></td><td><strong>{m.gallons} gal</strong></td><td>{m.previous.toLocaleString()} → <strong>{m.current.toLocaleString()} gal</strong></td><td>{m.reference}</td><td>{m.user}</td></tr>)}</tbody></table></div></section></div>
}
