import { AlertTriangle, ArrowDownRight, ArrowUpRight, Droplets, Gauge, Plus, Warehouse } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useApp } from '../context/AppContext'
import { formatDate, MetricCard, Modal, PageHeader, StatusBadge } from '../components/ui'

export function Inventory() {
  const { tanks, movements, catalogs, receiveFuel, notify, session } = useApp()
  const canReceive = ['ADMINISTRADOR', 'SUPERVISOR'].includes(session?.role || '')
  const [receptionOpen, setReceptionOpen] = useState(false)
  const totalStock = tanks.reduce((sum, tank) => sum + tank.stock, 0)
  const totalCapacity = tanks.reduce((sum, tank) => sum + tank.capacity, 0)
  const critical = tanks.filter((tank) => tank.stock <= tank.criticalLevel).length
  const received = movements.filter((m) => m.type === 'ENTRADA').reduce((sum, item) => sum + item.gallons, 0)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { if (await receiveFuel(Number(data.get('tank')), Number(data.get('gallons')), String(data.get('invoice')), { supplierId: Number(data.get('supplier')), date: String(data.get('date')), notes: String(data.get('notes')) })) setReceptionOpen(false); else notify('Capacidad excedida', 'El volumen recibido supera la capacidad disponible del tanque.', 'error') } catch (cause) { notify('No se pudo registrar', cause instanceof Error ? cause.message : 'Ocurrió un error inesperado.', 'error') } }
  return <div className="page"><PageHeader eyebrow="Combustible" title="Inventario en tiempo real" description="Consulta existencias, niveles críticos y capacidad disponible por tanque." actions={canReceive ? <button className="primary-button" onClick={() => setReceptionOpen(true)}><Plus size={17} /> Registrar recepción</button> : undefined} />
    <section className="metrics-grid metrics-3"><MetricCard label="Existencia total" value={`${totalStock.toLocaleString()} gal`} detail={`${totalCapacity ? Math.round(totalStock / totalCapacity * 100) : 0}% de la capacidad`} icon={<Droplets size={22} />} /><MetricCard label="Recibido recientemente" value={`${received.toLocaleString()} gal`} detail="Incluye recepciones registradas" icon={<ArrowUpRight size={22} />} tone="blue" /><MetricCard label="Tanques en nivel crítico" value={String(critical)} detail={critical ? 'Requiere atención inmediata' : 'Todos los niveles son normales'} icon={<AlertTriangle size={22} />} tone={critical ? 'red' : 'green'} /></section>
    <section className="inventory-cards">{tanks.map((tank) => { const percent = Math.round(tank.stock / tank.capacity * 100); const isCritical = tank.stock <= tank.criticalLevel; return <article className={`inventory-card ${isCritical ? 'is-critical' : ''}`} key={tank.id}><header><span className="tank-icon"><Warehouse size={22} /></span><span><strong>{tank.name}</strong><small>{tank.code} · {tank.station}</small></span><StatusBadge value={isCritical ? 'CRITICO' : 'NORMAL'} /></header><div className="inventory-number"><strong>{tank.stock.toLocaleString('es-DO')}</strong><span>galones disponibles</span></div><div className="gauge"><i className={isCritical ? 'critical' : ''} style={{ width: `${percent}%` }} /></div><div className="inventory-meta"><span><small>Capacidad</small><strong>{tank.capacity.toLocaleString()} gal</strong></span><span><small>Nivel crítico</small><strong>{tank.criticalLevel.toLocaleString()} gal</strong></span><span><small>Ocupación</small><strong>{percent}%</strong></span></div><footer><span><Gauge size={16} /> {tank.fuelType}</span><span className={isCritical ? 'text-red' : ''}>{isCritical ? 'Programar abastecimiento' : `${(tank.capacity - tank.stock).toLocaleString()} gal disponibles`}</span></footer></article> })}</section>
    <section className="panel table-panel"><div className="panel-header padded"><div><h2>Últimos movimientos</h2><p>Entradas, salidas y ajustes de inventario</p></div></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Movimiento</th><th>Tanque</th><th>Referencia</th><th>Usuario</th><th>Balance</th></tr></thead><tbody>{movements.map((movement) => <tr key={movement.id}><td>{formatDate(movement.date, true)}</td><td><span className={`movement-type ${movement.type === 'SALIDA' || movement.type.includes('NEGATIVO') ? 'out' : 'in'}`}>{movement.type === 'SALIDA' || movement.type.includes('NEGATIVO') ? <ArrowDownRight size={16} /> : <ArrowUpRight size={16} />}{movement.type.replace('_', ' ')}</span></td><td><strong>{movement.tank}</strong></td><td>{movement.reference}</td><td>{movement.user}</td><td><strong>{movement.current.toLocaleString()} gal</strong><small>{movement.type === 'SALIDA' || movement.type.includes('NEGATIVO') ? '-' : '+'}{movement.gallons} gal</small></td></tr>)}</tbody></table></div></section>
    {receptionOpen && <Modal title="Registrar recepción" subtitle="La entrada impactará el inventario del tanque seleccionado." onClose={() => setReceptionOpen(false)}><form className="form-grid" onSubmit={submit}><label>Proveedor<select name="supplier" required defaultValue=""><option value="" disabled>Seleccionar proveedor</option>{catalogs.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name} · {supplier.rnc}</option>)}</select></label><label>Número de factura<input name="invoice" placeholder="B010000000" required /></label><label>Tanque<select name="tank" required defaultValue=""><option value="" disabled>Seleccionar tanque</option>{tanks.map((tank) => <option key={tank.id} value={tank.id}>{tank.code} · {tank.fuelType}</option>)}</select></label><label>Volumen recibido (gal)<input name="gallons" type="number" min="0.1" step="0.1" required /></label><label>Fecha<input name="date" type="datetime-local" defaultValue={new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)} required /></label><label className="form-wide">Observaciones<textarea name="notes" rows={3} /></label><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setReceptionOpen(false)}>Cancelar</button><button className="primary-button">Registrar entrada</button></div></form></Modal>}
  </div>
}
